version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: desafio-crawler-api

    ports:
      - "3000:3000"

    env_file:
      - .env

    depends_on:
      redis:
        condition: service_healthy

    restart: unless-stopped

  redis:
    image: redis:7-alpine

    container_name: desafio-crawler-redis

    ports:
      - "6379:6379"

    command: redis-server --appendonly yes

    volumes:
      - redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

    restart: unless-stopped

volumes:
  redis_data: